name: Deploy to EC2

on:
  push:
    branches:
      - main

  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Debug secret presence
      run: | 
      shell: ${{ secrets.EC2_KEY }}"


    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Push files to EC2
      run: |
        rsync -avz --delete ./ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/app

    - name: Restart Nginx and App
      run: |
        ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          sudo cp /home/${{ secrets.EC2_USER }}/app/nginx.conf /etc/nginx/sites-available/default
          sudo nginx -t && sudo systemctl restart nginx
          cd /home/${{ secrets.EC2_USER }}/app
          npm run build || npm start &
        EOF
